CREATE TYPE notification_type_enum AS ENUM (
    'SINGLE',
    'GROUP'
);

CREATE TABLE notifications (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   message TEXT,
   notification_type notification_type_enum NOT NULL,
   recipient_id BIGINT, -- Soft FK to TaskSoft.users
   group_id BIGINT,     -- Soft FK to TaskSoft.user_groups
   task_id BIGINT NOT NULL -- Soft FK to TaskSoft.task
);

CREATE TABLE notification_reads (
    notification_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL, -- Soft FK to TaskSoft.users
    PRIMARY KEY (notification_id, user_id),
    -- We can only enforce the local relationship to the notification table
    CONSTRAINT fk_read_notification FOREIGN KEY (notification_id) REFERENCES notifications(id)
);

-- Indexes are highly recommended on soft foreign keys to speed up application-level lookups
CREATE INDEX idx_notifications_recipient_id ON notifications(recipient_id);
CREATE INDEX idx_notifications_task_id ON notifications(task_id);
CREATE INDEX idx_notification_reads_user_id ON notification_reads(user_id);